//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repuestos_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class facturasDetalle
    {
        public int facturaD_id { get; set; }
        public int factura_id { get; set; }
        public int producto_id { get; set; }
        public int facturaD_cantidad { get; set; }
        public decimal facturaD_precio { get; set; }
        public decimal facturaD_descuento { get; set; }
        public decimal facturaD_total { get; set; }
    
        public virtual Facturas Facturas { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
