//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repuestos_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordenDetalle
    {
        public int ordenD_id { get; set; }
        public int orden_id { get; set; }
        public int producto_id { get; set; }
        public int producto_cantidad { get; set; }
    
        public virtual ordenesCompra ordenesCompra { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
