//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repuestos_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordenesCompra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ordenesCompra()
        {
            this.ordenDetalle = new HashSet<ordenDetalle>();
        }
    
        public int orden_id { get; set; }
        public int proveedor_id { get; set; }
        public int estado_id { get; set; }
        public string orden_tipo { get; set; }
        public System.DateTime orden_fecha { get; set; }
        public string orden_facturarA { get; set; }
        public string orden_entregarA { get; set; }
        public string orden_descripcion { get; set; }
    
        public virtual Estados Estados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ordenDetalle> ordenDetalle { get; set; }
        public virtual Proveedores Proveedores { get; set; }
    }
}
