//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repuestos_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Productos()
        {
            this.facturasDetalle = new HashSet<facturasDetalle>();
            this.ordenDetalle = new HashSet<ordenDetalle>();
        }
    
        public int producto_id { get; set; }
        public int categoria_id { get; set; }
        public int estado_id { get; set; }
        public string producto_descripcion { get; set; }
        public int producto_existencias { get; set; }
        public decimal producto_precio { get; set; }
    
        public virtual Categorias Categorias { get; set; }
        public virtual Estados Estados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<facturasDetalle> facturasDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ordenDetalle> ordenDetalle { get; set; }
    }
}
