//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repuestos_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proveedores()
        {
            this.ordenesCompra = new HashSet<ordenesCompra>();
        }
    
        public int proveedor_id { get; set; }
        public string proveedor_cedula { get; set; }
        public string proveedor_nombre { get; set; }
        public string proveedor_apellido { get; set; }
        public string proveedor_correo { get; set; }
        public string proveedor_telefono { get; set; }
        public string proveedor_direccion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ordenesCompra> ordenesCompra { get; set; }
    }
}
